// render components ---

export const LOGIN_HANDLER = 'LOGIN_HANDLER';
export const REGISTER_PERSONDETAILS_HANDLER = 'REGISTER_PERSONDETAILS_HANDLER';
export const REGISTER_SOCIALMEDIA_HANDLER = 'REGISTER_SOCIALMEDIA_HANDLER';
export const REGISTER_PASSWORDDETAILS_HANDLER = 'REGISTER_PASSWORDDETAILS_HANDLER';

// loading bar ---

export const LOADING_BAR_START = 'LOADING_BAR_START';
export const LOADING_BAR_STOP = 'LOADING_BAR_STOP';


export const IMAGE_HANDLER='imageHandler';
